In [ ]:
import random
import matplotlib.pyplot as plt
x = range(2, 26, 2)  # x轴的位置
y = [random.randint(15, 30) for i in x]
plt.figure(figsize=(20, 8), dpi=80)
# 不设置标签，就是默认的自增
x_table = ['{}:00'.format(i) for i in x]
plt.xticks(x, x_table, rotation=45)
y_table = tuple('{}:00'.format(i) for i in y)
plt.yticks(y, y_table)
plt.plot(x, y)

In [ ]:
from matplotlib import font_manager

x = range(0, 120)
y = [random.randint(10, 30) for i in range(120)]
plt.figure(figsize=(20, 8), dpi=80)
plt.plot(x, y)
# size是字的大小
my_font = font_manager.FontProperties(fname='C:\Windows\Fonts\STSONG.TTF', size=180)
# 必须写fontproperties= my_font，不然显示的就是小方格
plt.xlabel('时间', rotation=45, fontproperties=my_font)
plt.ylabel('次数', fontproperties=my_font)
plt.title('每分钟跳动次数', color='red', fontproperties=my_font)

In [ ]:
y1 = [1, 0, 1, 1, 2, 4, 3, 4, 4, 5, 6, 5, 4, 3, 3, 1, 1, 1, 1, 1]
y2 = [1, 0, 3, 1, 2, 2, 3, 4, 3, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1]

x = range(11, 31)
plt.figure(figsize=(20, 8), dpi=80)
my_font = font_manager.FontProperties(fname='C:\Windows\Fonts\STSONG.TTF', size=18)
plt.plot(x, y1, label='小明')
plt.plot(x, y2, label='小钱')
x_label = ['{}岁'.format(i) for i in x]
plt.xticks(x, x_label, fontproperties=my_font, rotation=45)
plt.grid(alpha=0.4)
plt.legend(prop=my_font, loc='upper right')

In [ ]:
# 横着分为两块，竖着分了两块，总共四块
a, axes = plt.subplots(2, 2)
ax1 = axes[0, 0]
ax2 = axes[0, 1]
ax3 = axes[1, 0]
ax4 = axes[1, 1]
# 总图大小
fig = plt.figure(figsize=(20, 8), dpi = 80)
x = [i for i in range(100)]
ax1.plot(x, x)

In [ ]:
x = [i for i in range(100)]
y = [i**2 for i in range(100)]
fig = plt.figure(figsize=(20, 10), dpi=80)
# means split the picture to four parts, and get NO.1
ax1 = fig.add_subplot(2, 2, 1)
ax2 = fig.add_subplot(2, 2, 2)
ax3 = fig.add_subplot(2, 2, 3)
ax14= fig.add_subplot(2, 2, 4)
ax1.plot(x, x)
ax2.plot(x, y)
ax3.plot(y, x)
ax4.plot(y, y)

In [ ]:
y = [11, 17, 16, 11, 12, 11, 12, 6, 6, 7, 8, 9, 12, 15, 14, 17, 18, 21, 16, 17, 20, 14,
15, 15, 15, 19, 21, 22, 22, 22,
23]
x = range( 1, 32 )
plt.figure(figsize=(20, 8),dpi=80)
plt.scatter(x, y, label = 'April')
my_font = font_manager.FontProperties( fname='C:\Windows\Fonts\STSONG.TTF', size=10 )
x_label = ['3月{}日'.format(i) for i in x]
# 做切片
plt.xticks(x[::3], x_label[::3], fontproperties = my_font, rotation = 45)
plt.xlabel('日期', fontproperties = my_font)
plt.ylabel('温度', fontproperties = my_font)
plt.legend(prop = my_font)

In [ ]:
my_font = font_manager.FontProperties(fname='C:\Windows\Fonts\STSONG.TTF',size=16)
a = ['流浪地球','疯狂的外星人','飞驰人生','大黄蜂','熊出没·原始时代','新喜剧之王']
b = [38.13,19.85,14.89,11.36,6.47,5.93]
plt.figure(figsize=(20,8),dpi=80)
reacts = plt.bar(range(len(a)), b, width = 0.3)
# rect就是每个柱子对象
for rect in reacts:
    height = rect.get_height()
    # 横坐标，纵坐标，内容，ha = 'center'代表将添加的文本放在中间，可以是left/right可以放在不同的位置
    plt.text(rect.get_x() + rect.get_width() / 2, height+0.3, str(height),ha="center")
plt.xticks(range(len(a)), a, fontproperties = my_font)
plt.legend(prop = my_font)

In [ ]:
time = [131, 98, 125, 131, 124, 139, 131, 117, 128, 108, 135, 138, 131, 102,
107, 114,
119, 128, 121, 142, 127, 130, 124, 101, 110, 116, 117, 110, 128, 128, 115,
99,
136, 126, 134, 95, 138, 117, 111,78, 132, 124, 113, 150, 110, 117, 86,
95, 144,
105, 126, 130,126, 130, 126, 116, 123, 106, 112, 138, 123, 86, 101, 99, 136,123,
117, 119, 105, 137, 123, 128, 125, 104, 109, 134, 125, 127,105, 120, 107, 129,
116,
108, 132, 103, 136, 118, 102, 120, 114,105, 115, 132, 145, 119, 121, 112, 139,
125,
138, 109, 132, 134,156, 106, 117, 127, 144, 139, 139, 119, 140, 83, 110,
102,123,
107, 143, 115, 136, 118, 139, 123, 112, 118, 125, 109, 119, 133,112, 114, 122,
109,
106, 123, 116, 131, 127, 115, 118, 112, 135,115, 146, 137, 116, 103,
144, 83, 123,
111, 110, 111, 100, 154,136, 100, 118, 119, 133, 134, 106, 129, 126,
110, 111, 109,
141,120, 117, 106, 149, 122, 122, 110, 118, 127, 121, 114, 125, 126,114, 140, 103,
130, 141, 117, 106, 114, 121, 114, 133, 137, 92,121, 112, 146, 97, 137,
105, 98,
117, 112, 81, 97, 139, 113,134, 106, 144, 110, 137, 137, 111, 104, 117,
100, 111,
101, 110,105, 129, 137, 112, 120, 113, 133, 112, 83, 94, 146, 133,
101,131, 116,
111, 84, 137, 115, 122, 106, 144, 109, 123, 116, 111,111, 133, 150]
my_font = font_manager.FontProperties(fname='C:\Windows\Fonts\STSONG.TTF',size=18)
plt.figure(figsize=(20, 8), dpi=80)
# 每个柱形占多少
distance = 2
group_num = int((max(time) - min(time))/distance)
plt.hist(time, bins=group_num)
plt.xticks(range(min(time), max(time))[::2])
plt.grid(alpha = 0.4)
plt.xlabel("电影时长大小",fontproperties=my_font)
plt.ylabel("电影的数据量",fontproperties=my_font)

In [ ]:
import matplotlib
label_list = ["第一部分", "第二部分", "第三部分"]
# 各部分标签
size = [55, 35, 10]
# 各部分大小,按比例
color = ["black", "white", "gray"]
# 各部分颜色
explode = [0, 0.05, 0]
# 各部分突出值
# 下面是为了显示中文，因为再pie里没有fontproperties这个参数，所以只有用这种方法
matplotlib.rcParams['font.sans-serif']=['SimHei']
patches, l_text, p_text = plt.pie(size,explode=explode, colors=color, labels=label_list,
labeldistance=1.1, autopct="%1.1f%%", shadow=False,
startangle=90, pctdistance=0.6)
plt.axis("equal")
# 设置横轴和纵轴大小相等，这样饼才是圆的
plt.legend()

In [ ]:
import time
import numpy as np

info_list = [i for i in range(1000000)]
atime = time.time()
print(sum(info_list))
btime = time.time()
print(btime-atime)
info_array = np.array(info_list)
ctime = time.time()
print(np.sum(info_array))
dtime = time.time()
print(dtime-ctime)

In [ ]:
info_list = [1, 2, 3, 4]
info_array = np.array(info_list)
print(info_array.ndim)
print(info_array.shape)
print(info_array.size)

In [ ]:
info_array = np.arange(10)
print(info_array)

In [2]:
import numpy as np
info_array = np.array([[1, 2], [3, 4], [5, 6]])
print(info_array)
print(info_array.ndim)
print(info_array.shape)
print(info_array.size)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
6


In [ ]:
info_array = np.array([[1, 2], [3, 4], [5, 6]])
info_array.shape = (6,)
print(info_array)
print(info_array.reshape(2, 3))


In [ ]:
info_array = np.array([[1, 2], [3, 4], [5, 6]])
info_list = info_array.tolist()
print(info_list)

In [6]:
info = np.arange(27).reshape(3,3,3)
print(info)
v1 = [[0,1,2,3,4,5],
[6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],
[18,19,20,21,22,23]]
result = np.hstack((v1,v2))
print(result)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


In [17]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [27]:
a=np.arange(16).reshape((2,2,2,2))
print(np.sum(a))
print(a)
b=np.sum(a, axis=0)
print("-"*20)
print(b)
print("-"*20)
b=np.sum(a, axis=2)
print(b)
print("-"*20)
b=np.sum(a, axis=1)
print(b)

120
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
--------------------
[[[ 8 10]
  [12 14]]

 [[16 18]
  [20 22]]]
--------------------
[[[ 2  4]
  [10 12]]

 [[18 20]
  [26 28]]]
--------------------
[[[ 4  6]
  [ 8 10]]

 [[20 22]
  [24 26]]]


In [24]:
t1 = np.arange(24).reshape(4,6)
print(t1[[0,2,3]])# 取不连续的多行
print(t1[0:3])
print(t1[[1,2,0]])
print(t1[[0,2],0:1])

[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [ 0  1  2  3  4  5]]
[[ 0]
 [12]]


In [28]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print('第一个数组：')
print(a)
print('\n')
print(' 向 数 组 添 加 元 素 ：')
print(np.append(a, [7, 8, 9]))
print('\n')
print('沿轴 0 添加元素：')
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')
print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))

第一个数组：
[[1 2 3]
 [4 5 6]]


 向 数 组 添 加 元 素 ：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [29]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print('沿轴 0 广播：')
print(np.insert(a, 1, [11], axis=0))
print('\n')
print('沿轴 1 广播：')
print(np.insert(a, 1, 11, axis=1))

沿轴 0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴 1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [32]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
# 要求 a,b 两个数组的维度相同
# print ('沿轴 0 连接两个数组：')
print (np.concatenate((a,b),axis= 0))
print ('\n')
print ('沿轴 1 连接两个数组：')
print (np.concatenate((a,b),axis = 1))
print ('沿轴 0 连接两个数组：')
print (np.stack((a,b),axis= 0))
print ('\n')
print ('沿轴 1 连接两个数组：')
print (np.stack((a,b),axis = 1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]
沿轴 0 连接两个数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


沿轴 1 连接两个数组：
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [33]:
v1 = [[0,1,2,3,4,5],
[6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],
[18,19,20,21,22,23]]
result = np.vstack((v1,v2))
print(result)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [34]:
v1 = [[0,1,2,3,4,5],
[6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],
[18,19,20,21,22,23]]
result = np.hstack((v1,v2))
print(result)

[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


In [35]:
arr = np.arange(9).reshape(3,3)
print ('将数组分为三个大小相等的子数组：')
b = np.split(arr,3)
print (b)

将数组分为三个大小相等的子数组：
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


In [38]:
harr = np.floor(10*np.random.random((2, 6)))
print ('原 array：')
print(harr)
print ('拆分后：')
print(np.hsplit(harr, 2))

原 array：
[[3. 8. 4. 1. 3. 3.]
 [6. 2. 4. 2. 1. 1.]]
拆分后：
[array([[3., 8., 4.],
       [6., 2., 4.]]), array([[1., 3., 3.],
       [2., 1., 1.]])]


In [56]:
t = np.arange(24,dtype=float).reshape(4,6)
t[1,3:] = np.nan
print(t)
for i in range(t.shape[1]):#获取当前列数据
    temp_col = t[:,i]
    # 判断当前列的数据中是否含有 nan
    nan_num = np.count_nonzero(temp_col != temp_col)# 条件成立说明含有 nan
    if nan_num != 0:
        # 将这一列不为 nan 的数据拿出来
        temp_col_not_nan = temp_col[temp_col == temp_col]# 将 nan 替换成这一列的平均值
        print('temp_col_not_nan')
        print(temp_col_not_nan)
        temp_col[np.isnan( temp_col )] = np.mean( temp_col_not_nan )

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
temp_col_not_nan
[ 3. 15. 21.]
temp_col_not_nan
[ 4. 16. 22.]
temp_col_not_nan
[ 5. 17. 23.]


array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8., 13., 14., 15.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [62]:
import numpy as np
from matplotlib import pyplot as plt
us_file_path = "./youtube_video_data/US_video_data_numbers.csv"
uk_file_path = "./youtube_video_data/GB_video_data_numbers.csv"
# t1 = np.loadtxt(us_file_path,delimiter=",",dtype="int",unpack=True)
t_us = np.loadtxt(us_file_path,delimiter=",",dtype="int")
#取评论的数据
t_us_comments = t_us[:,-1]
#选择比 5000 小的数据
t_us_comments = t_us_comments[t_us_comments<=5000]
print(t_us_comments.max(),t_us_comments.min())
d = 50
bin_nums = (t_us_comments.max()-t_us_comments.min())//d
#绘图
plt.figure(figsize=(20,8),dpi=80)
plt.hist(t_us_comments,bin_nums)
plt.show()

UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 667: illegal multibyte sequence